import {
  Student,
  Teacher,
  Admin,
  Course,
  Certificate,
  StudentPayment,
  EnrolledCourse,
  Announcement,
  StudentProgressRecord,
  UploadedResource,
  AdminManagedCourse,
  EnrollmentRequest,
  CourseMaterial,
  TeachingCourse,
  UpcomingClass,
} from "@/types";

export const mockAdmin: Admin = {
  id: "admin01",
  uid: "uid_admin_001",
  role: "admin",
  name: "Admin User",
  email: "admin@Cornoracademy.com",
  avatar: "/admin-avatar.png",
  status: "active",
  gender: "other",
  dob: "N/A",
  createdAt: "2023-01-01",
  updatedAt: "2024-01-01",
};

export const mockStudentData: Student = {
  id: "1",
  uid: "STU001",
  role: "student",
  name: "Alex Johnson",
  email: "alex.johnson@email.com",
  status: "active",
  enrolledCourses: ["1", "2", "4"],
  completedCourses: ["3"],
  totalLearningHours: 156,
  currentStreak: 12,
  avatar: "/student-avatar.png",
  gender: "male",

  dob: "1995-03-15",
  createdAt: "2024-01-01",
  updatedAt: "2024-01-20",
};

export const mockTeacherData: Teacher = {
  id: "1",
  uid: "TCH001",
  role: "teacher",
  name: "Rajan Koirala",
  title: "Senior Full-Stack Developer",
  email: "rajan.koirala@cornoracademy.com",
  bio: "Experienced full-stack developer and passionate educator with 12+ years in the tech industry.",
  status: "active",
  avatar: "/teacher-avatar.png",
  gender: "male",
  dob: "1985-07-22",
  createdAt: "2023-01-01",
  updatedAt: "2024-01-20",
};

export const mockTeacherBikash: Teacher = {
  id: "2",
  uid: "TCH005",
  role: "teacher",
  name: "Bikash Thapa",
  title: "Data Scientist",
  email: "bikash.thapa@cornoracademy.com",
  bio: "Data scientist with industry experience in analytics and ML deployments.",
  status: "active",
  avatar: "/teacher-avatar.png",
  gender: "male",
  dob: "1986-04-11",
  createdAt: "2023-04-01",
  updatedAt: "2024-04-01",
};

export const mockTeacherAnil: Teacher = {
  id: "3",
  uid: "TCH006",
  role: "teacher",
  name: "Anil Adhikari",
  title: "Marketing Lead",
  email: "anil.adhikari@cornoracademy.com",
  bio: "Digital marketing professional with years of agency experience running campaigns.",
  status: "active",
  avatar: "/teacher-avatar.png",
  gender: "male",
  dob: "1987-09-02",
  createdAt: "2023-05-01",
  updatedAt: "2024-05-01",
};

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Web Development Fundamentals",
    description:
      "Master the fundamentals of web development with HTML, CSS, JavaScript, and modern frameworks.",
    longDescription:
      "This comprehensive course covers everything you need to know to become a proficient web developer. Starting with the basics of HTML and CSS, you'll progress through JavaScript fundamentals, responsive design principles, and modern development tools. By the end of this course, you'll have built multiple projects and have the skills to create professional websites and web applications.",
    instructor: mockTeacherData,
    price: 29900,
    originalPrice: 39900,
    duration: "12 weeks",
    level: "beginner",
    language: "english",
    students: 2840,
    rating: 4.9,
    reviews: 1250,
    status: "active",
    certificate: true,
    thumbnail: "/courses/web-dev.png",
    modules: [
      { title: "Introduction to Web Development", lessons: 4, duration: "1.5 hours" },
      { title: "HTML Fundamentals", lessons: 12, duration: "4 hours" },
      { title: "CSS Styling and Layout", lessons: 15, duration: "5 hours" },
      { title: "JavaScript Basics (ES6+)", lessons: 20, duration: "6 hours" },
      { title: "DOM & Event Handling", lessons: 8, duration: "3 hours" },
      { title: "Build Tools & Version Control", lessons: 6, duration: "2.5 hours" },
      { title: "Intro to React", lessons: 18, duration: "6 hours" },
      { title: "Backend Basics (Node.js)", lessons: 10, duration: "4 hours" },
      { title: "Testing & Deployment", lessons: 6, duration: "2.5 hours" },
      { title: "Final Project & Portfolio", lessons: 6, duration: "5 hours" },
    ],
    features: [
      "76 video lessons",
      "23 hours of content",
      "7 hands-on projects",
      "Lifetime access",
      "Certificate of completion",
      "Direct instructor support",
      "Mobile and desktop access",
      "30-day money-back guarantee",
    ],
    requirements: [
      "No prior programming experience required",
      "A computer with internet connection",
      "Willingness to learn and practice",
    ],
    outcomes: [
      "Build responsive websites from scratch",
      "Understand HTML, CSS, and JavaScript fundamentals",
      "Use modern development tools and workflows",
      "Create interactive web applications",
      "Deploy projects to the web",
      "Start a career in web development",
    ],
  },
  {
    id: "2",
    title: "Data Science & Analytics",
    description:
      "Learn data science fundamentals, statistical analysis, and machine learning with Python. Work with real datasets and build predictive models.",
    longDescription:
      "Dive deep into the world of data science with this comprehensive course. You will learn Python programming, statistical analysis, data visualization, and machine learning algorithms. Through hands-on projects with real-world datasets, you will develop the skills needed to extract insights from data and build predictive models.",
    instructor: mockTeacherBikash,
    price: 39900,
    originalPrice: 49900,
    duration: "16 weeks",
    level: "intermediate",
    students: 1920,
    rating: 4.8,
    reviews: 890,
    language: "english",
    status: "active",
    certificate: true,
    modules: [
      { title: "Python for Data Science", lessons: 16, duration: "5 hours" },
      { title: "Data Wrangling with Pandas", lessons: 12, duration: "4 hours" },
      { title: "Exploratory Data Analysis", lessons: 10, duration: "3.5 hours" },
      { title: "Data Visualization (Matplotlib & Seaborn)", lessons: 8, duration: "3 hours" },
      { title: "Statistical Foundations", lessons: 10, duration: "4 hours" },
      { title: "Machine Learning Basics", lessons: 18, duration: "6 hours" },
      { title: "Model Evaluation & Tuning", lessons: 8, duration: "3 hours" },
      { title: "Deploying Models", lessons: 6, duration: "3 hours" },
      { title: "Capstone Project", lessons: 6, duration: "8 hours" },
    ],
    features: [
      "77 video lessons",
      "25.5 hours of content",
      "5 real-world projects",
      "Jupyter notebooks included",
      "Certificate of completion",
      "Career guidance",
      "Community access",
      "30-day money-back guarantee",
    ],
    requirements: [
      "Basic programming knowledge helpful",
      "High school level mathematics",
      "Computer with Python installation capability",
    ],
    outcomes: [
      "Master Python for data analysis",
      "Perform statistical analysis on datasets",
      "Create compelling data visualizations",
      "Build machine learning models",
      "Work with real-world data problems",
      "Launch a career in data science",
    ],
    thumbnail: "/courses/data-science.png",
  },
  {
    id: "3",
    title: "Digital Marketing Mastery",
    description:
      "Master digital marketing strategies including SEO, social media, content marketing, and paid advertising. Grow your business or career.",
    longDescription:
      "This comprehensive digital marketing course covers all aspects of modern marketing. From SEO and content marketing to social media advertising and analytics, you will learn proven strategies to grow businesses online. Perfect for entrepreneurs, marketers, and business owners.",
    instructor: mockTeacherAnil,
    price: 24900,
    originalPrice: 34900,
    duration: "10 weeks",
    level: "beginner",
    students: 3150,
    rating: 4.9,
    reviews: 1680,
    language: "english",
    status: "completed",
    certificate: true,
    modules: [
      { title: "Digital Marketing Fundamentals", lessons: 8, duration: "3 hours" },
      { title: "Content Strategy & Copywriting", lessons: 10, duration: "4 hours" },
      { title: "SEO (On-page & Technical)", lessons: 12, duration: "4.5 hours" },
      { title: "Social Media Campaigns", lessons: 10, duration: "4 hours" },
      { title: "Paid Advertising (Google & Meta)", lessons: 10, duration: "4 hours" },
      { title: "Email Marketing & Automation", lessons: 6, duration: "2.5 hours" },
      { title: "Analytics & Conversion Optimization", lessons: 8, duration: "3 hours" },
      { title: "Practical Campaign Project", lessons: 6, duration: "6 hours" },
    ],
    features: [
      "64 video lessons",
      "19 hours of content",
      "6 marketing campaigns",
      "Templates and tools included",
      "Certificate of completion",
      "Live Q&A sessions",
      "Marketing toolkit",
      "30-day money-back guarantee",
    ],
    requirements: [
      "No prior marketing experience required",
      "Basic computer skills",
      "Access to social media platforms",
    ],
    outcomes: [
      "Create effective marketing strategies",
      "Master SEO and content marketing",
      "Run successful social media campaigns",
      "Set up and optimize paid ads",
      "Analyze marketing performance",
      "Grow your business or career",
    ],
    thumbnail: "/courses/digital-marketing.png",
  },
  {
    id: "4",
    title: "Graphic Design Essentials",
    description:
      "Learn core graphic design principles, Photoshop and Illustrator workflows, and visual composition.",
    longDescription:
      "This course covers typography, color theory, layout, and hands-on projects in Photoshop and Illustrator to build a professional design portfolio.",
    instructor: {
      id: "2",
      uid: "TCH002",
      role: "teacher",
      name: "Ram Bahadur",
      title: "Graphic Designer",
      email: "ram.bahadur@cornoracademy.com",
      bio: "Experienced graphic designer and creative instructor.",
      status: "active",
      avatar: "/teacher-avatar.png",
      gender: "male",
      dob: "1988-05-10",
      createdAt: "2023-01-05",
      updatedAt: "2024-02-01",
    },
    price: 19900,
    originalPrice: 24900,
    duration: "8 weeks",
    level: "beginner",
    language: "nepali",
    students: 1250,
    rating: 4.7,
    reviews: 320,
    status: "active",
    certificate: true,
    thumbnail: "/courses/graphics-design.png",
    modules: [
      { title: "Principles of Design", lessons: 6, duration: "2 hours" },
      { title: "Typography & Type Systems", lessons: 8, duration: "3 hours" },
      { title: "Color Theory & Composition", lessons: 8, duration: "3.5 hours" },
      { title: "Adobe Photoshop Essentials", lessons: 10, duration: "4 hours" },
      { title: "Adobe Illustrator Essentials", lessons: 10, duration: "4 hours" },
      { title: "Branding & Visual Identity", lessons: 6, duration: "3 hours" },
      { title: "Portfolio Project", lessons: 6, duration: "6 hours" },
    ],
    features: ["Hands-on projects", "Source files", "Portfolio guidance"],
    requirements: ["Basic computer skills"],
    outcomes: ["Create professional graphics", "Build a design portfolio"],
  },
  {
    id: "5",
    title: "Photography Basics",
    description: "Master camera fundamentals, composition and editing for stunning photos.",
    longDescription:
      "A practical photography course covering exposure, composition, lighting, and editing techniques for beginners.",
    instructor: {
      id: "3",
      uid: "TCH003",
      role: "teacher",
      name: "Suman Rai",
      title: "Photographer",
      email: "suman.rai@cornoracademy.com",
      bio: "Professional photographer and instructor with commercial experience.",
      status: "active",
      avatar: "/teacher-avatar.png",
      gender: "male",
      dob: "1990-02-14",
      createdAt: "2023-02-01",
      updatedAt: "2024-02-10",
    },
    price: 17900,
    originalPrice: 22900,
    duration: "6 weeks",
    level: "beginner",
    language: "nepali",
    students: 980,
    rating: 4.6,
    reviews: 210,
    status: "active",
    certificate: true,
    thumbnail: "/courses/web-security.png",
    modules: [
      { title: "Camera Basics & Exposure", lessons: 6, duration: "3 hours" },
      { title: "Composition & Framing", lessons: 8, duration: "3 hours" },
      { title: "Lighting for Photography", lessons: 8, duration: "4 hours" },
      { title: "Portrait & Landscape Techniques", lessons: 6, duration: "3 hours" },
      { title: "Editing Workflow (Lightroom & Photoshop)", lessons: 8, duration: "4 hours" },
      { title: "Practical Assignments & Portfolio", lessons: 6, duration: "6 hours" },
    ],
    features: ["Editing demos", "Practical assignments"],
    requirements: ["Camera (phone or DSLR)"],
    outcomes: ["Shoot better photos", "Basic editing skills"],
  },
  {
    id: "6",
    title: "3D Animation Basics",
    description: "Introduction to 3D modeling and animation workflows.",
    longDescription:
      "Learn the fundamentals of 3D modeling, texturing and simple animation using industry tools.",
    instructor: {
      id: "4",
      uid: "TCH004",
      role: "teacher",
      name: "Pradeep Shrestha",
      title: "3D Artist",
      email: "pradeep.shrestha@cornoracademy.com",
      bio: "3D artist and animator with experience in films and games.",
      status: "active",
      avatar: "/teacher-avatar.png",
      gender: "male",
      dob: "1987-11-02",
      createdAt: "2023-03-01",
      updatedAt: "2024-03-01",
    },
    price: 34900,
    originalPrice: 44900,
    duration: "14 weeks",
    level: "intermediate",
    language: "english",
    students: 540,
    rating: 4.5,
    reviews: 98,
    status: "active",
    certificate: true,
    thumbnail: "/courses/3D-animation.png",
    modules: [
      { title: "Intro to 3D & Tools", lessons: 6, duration: "3 hours" },
      { title: "Modeling Basics", lessons: 12, duration: "6 hours" },
      { title: "Texturing & Shading", lessons: 8, duration: "4 hours" },
      { title: "Rigging & Animation Basics", lessons: 10, duration: "5 hours" },
      { title: "Lighting & Rendering", lessons: 8, duration: "4 hours" },
      { title: "Final Animation Project", lessons: 6, duration: "8 hours" },
    ],
    features: ["Project-based", "Model files included"],
    requirements: ["Desktop with GPU"],
    outcomes: ["Create simple 3D animations"],
  },
];

export const mockEnrolledCourses: EnrolledCourse[] = [
  {
    id: 1,
    title: "Web Development Fundamentals",
    instructor: "Sarah Johnson",
    progress: 75,
    totalLessons: 24,
    completedLessons: 18,
    nextLesson: "JavaScript Functions",
    thumbnail: "/web-development-course.png",
    status: "in-progress",
    lastAccessed: "2 hours ago",
    startTime: "2024-01-20 14:00",
    nextClassTime: "Today at 2:00 PM",
    meetingLink: "https://meet.example.com/web-dev-class",
  },
  {
    id: 2,
    title: "Data Science & Analytics",
    instructor: "Dr. Michael Chen",
    progress: 45,
    totalLessons: 32,
    completedLessons: 14,
    nextLesson: "Data Visualization",
    thumbnail: "/data-science-course.png",
    status: "in-progress",
    lastAccessed: "1 day ago",
    startTime: "2024-01-15 10:00",
    nextClassTime: "Tomorrow at 10:00 AM",
    meetingLink: "https://meet.example.com/data-sci-class",
  },
  {
    id: 3,
    title: "Digital Marketing Mastery",
    instructor: "Emma Rodriguez",
    progress: 100,
    totalLessons: 20,
    completedLessons: 20,
    nextLesson: "Course Completed",
    thumbnail: "/digital-marketing-course.png",
    status: "completed",
    lastAccessed: "3 days ago",
    startTime: "2023-12-01 09:00",
    nextClassTime: "Course Completed",
    meetingLink: "",
  },
  {
    id: 4,
    title: "UI/UX Design Principles",
    instructor: "David Kim",
    progress: 20,
    totalLessons: 28,
    completedLessons: 6,
    nextLesson: "Color Theory",
    thumbnail: "/ui-ux-design-course.png",
    status: "in-progress",
    lastAccessed: "5 days ago",
    startTime: "2024-01-10 11:00",
    nextClassTime: "Jan 25 at 11:00 AM",
    meetingLink: "https://meet.example.com/ui-ux-class",
  },
];

export const mockStudentPayments: StudentPayment[] = [
  {
    id: 1,
    studentName: "John Smith",
    studentEmail: "john.smith@email.com",
    amount: 299,
    status: "completed",
    paymentMethod: "Credit Card",
    date: "2024-01-15",
    transactionId: "TXN001",
    avatar: "/student-avatar.png",
  },
  {
    id: 2,
    studentName: "Sarah Wilson",
    studentEmail: "sarah.wilson@email.com",
    amount: 224.25,
    status: "partial",
    paymentMethod: "PayPal",
    date: "2024-01-14",
    transactionId: "TXN002",
    avatar: "/student-avatar-2.png",
  },
  {
    id: 3,
    studentName: "Michael Brown",
    studentEmail: "michael.brown@email.com",
    amount: 299,
    status: "completed",
    paymentMethod: "Bank Transfer",
    date: "2024-01-10",
    transactionId: "TXN003",
    avatar: "/student-avatar-3.png",
  },
  {
    id: 4,
    studentName: "Emma Davis",
    studentEmail: "emma.davis@email.com",
    amount: 0,
    status: "pending",
    paymentMethod: "-",
    date: "-",
    transactionId: "-",
    avatar: "/student-avatar-4.png",
  },
  {
    id: 5,
    studentName: "Alex Johnson",
    studentEmail: "alex.johnson@email.com",
    amount: 299,
    status: "completed",
    paymentMethod: "Credit Card",
    date: "2024-01-08",
    transactionId: "TXN004",
    avatar: "/student-avatar-5.png",
  },
];

export const mockAdminManagedCourses: AdminManagedCourse[] = [
  {
    id: 1,
    title: "Web Development Fundamentals",
    instructor: "Dr. Sarah Johnson",
    instructorId: 1,
    students: 67,
    price: 299,
    status: "active",
    created: "2023-12-01",
    completion: 85,
    rating: 4.8,
    enrolled: 67,
    startTime: "2024-01-20 14:00",
    description: "Learn web development from scratch",
  },
  // ... other managed course objects
];

export const mockEnrollmentRequests: EnrollmentRequest[] = [
  {
    id: 1,
    studentName: "John Smith",
    studentEmail: "john.smith@email.com",
    courseTitle: "Web Development Fundamentals",
    courseId: 1,
    paymentScreenshotUrl: "/generic-payment-screenshot.png",
    status: "pending",
    createdAt: "2024-01-20",
    amount: 299,
  },
  // ... other requests
];

export const mockStudentProgress: StudentProgressRecord[] = [
  {
    id: 1,
    name: "Alex Johnson",
    email: "alex.johnson@email.com",
    progress: 85,
    lastActive: "2 hours ago",
    attendance: 92,
    assignments: "8/10",
    avatar: "/student-avatar.png",
  },
  // ... other progress records
];

export const mockUploadedResources: UploadedResource[] = [
  {
    id: 1,
    name: "JavaScript Fundamentals.pdf",
    type: "pdf",
    size: "2.4 MB",
    folder: "Week 1 - Introduction",
    uploadDate: "2024-01-15",
    downloads: 45,
    description: "Complete guide to JavaScript basics...",
  },
  // ... other resources
];

export const mockCertificates: Record<string, Certificate> = {
  "CA-2024-WD-001234": {
    id: "CA-2024-WD-001234",
    studentId: "1",
    studentName: "John Doe",
    courseId: "1",
    courseName: "Web Development Fundamentals",
    instructor: "Sarah Johnson",
    completionDate: "March 15, 2024",
    issueDate: "March 16, 2024",
    grade: "A+",
    creditsEarned: 12,
    status: "valid",
    skills: ["HTML5", "CSS3", "JavaScript", "Responsive Design", "Git"],
  },
  "CA-2024-DS-005678": {
    id: "CA-2024-DS-005678",
    studentId: "2",
    studentName: "Jane Smith",
    courseId: "2",
    courseName: "Data Science & Analytics",
    instructor: "Dr. Michael Chen",
    completionDate: "February 28, 2024",
    issueDate: "March 1, 2024",
    grade: "A",
    creditsEarned: 16,
    status: "valid",
    skills: [
      "Python",
      "Pandas",
      "Machine Learning",
      "Data Visualization",
      "Statistics",
    ],
  },
  "CA-2023-DM-009876": {
    id: "CA-2023-DM-009876",
    studentId: "3",
    studentName: "Mike Johnson",
    courseId: "3",
    courseName: "Digital Marketing Mastery",
    instructor: "Emma Rodriguez",
    completionDate: "December 10, 2023",
    issueDate: "December 11, 2023",
    grade: "B+",
    creditsEarned: 10,
    status: "valid",
    skills: [
      "SEO",
      "Social Media Marketing",
      "Google Analytics",
      "Content Marketing",
      "PPC",
    ],
  },
};

export const mockTeachingCourses: TeachingCourse[] = [
  {
    id: 1,
    title: "Web Development Fundamentals",
    students: 67,
    totalLessons: 24,
    completedLessons: 18,
    avgProgress: 75,
    nextClass: "Today, 2:00 PM",
    status: "active",
    startTime: "2024-01-20 14:00",
  },
  {
    id: 2,
    title: "Advanced JavaScript Concepts",
    students: 45,
    totalLessons: 20,
    completedLessons: 12,
    avgProgress: 60,
    nextClass: "Tomorrow, 10:00 AM",
    status: "active",
    startTime: "2024-01-21 10:00",
  },
  {
    id: 3,
    title: "React Development Mastery",
    students: 44,
    totalLessons: 28,
    completedLessons: 28,
    avgProgress: 100,
    nextClass: "Course Completed",
    status: "completed",
    startTime: "2023-12-01 09:00",
  },
];

export const mockUpcomingClasses: UpcomingClass[] = [
  {
    id: 1,
    title: "JavaScript Functions & Scope",
    course: "Web Development Fundamentals",
    courseId: 1,
    date: "Today",
    time: "2:00 PM",
    duration: "1.5 hours",
    students: 67,
    meetingLink: "https://meet.example.com/js-functions",
  },
  {
    id: 2,
    title: "Async Programming Workshop",
    course: "Advanced JavaScript Concepts",
    courseId: 2,
    date: "Tomorrow",
    time: "10:00 AM",
    duration: "2 hours",
    students: 45,
    meetingLink: "https://meet.example.com/async-js",
  },
];

export const mockSystemActivity = [
  {
    id: 1,
    type: "user_registration",
    description: "New student registered: John Smith",
    timestamp: "2 hours ago",
    severity: "info",
  },
  {
    id: 2,
    type: "course_completion",
    description: "Course completed: React Development Mastery by Sarah Wilson",
    timestamp: "4 hours ago",
    severity: "success",
  },
  {
    id: 3,
    type: "payment_failed",
    description: "Payment failed for Emma Davis - Data Science Fundamentals",
    timestamp: "6 hours ago",
    severity: "warning",
  },
  {
    id: 4,
    type: "teacher_added",
    description: "New teacher added: Dr. Emily Davis",
    timestamp: "1 day ago",
    severity: "info",
  },
];

export const mockRecentAnnouncements: Announcement[] = [
  {
    id: 1,
    type: "assignment",
    title: "Assignment Deadline Extended",
    course: "Web Development Fundamentals",
    courseId: "1",
    message:
      "The JavaScript project deadline has been extended to next Monday.",
    time: "2 hours ago",
    date: "2025 Nov 11",
    recipients: 67,
  },
  {
    id: 2,
    type: "update",
    title: "New Learning Resources Added",
    course: "Advanced JavaScript Concepts",
    courseId: "2",
    message: "I've added additional practice exercises for async programming.",
    time: "1 day ago",
    date: "2025 Nov 1",
    recipients: 45,
  },
];

export const mockCourseAnnouncements: Announcement[] = [
  {
    id: 1,
    title: "New Assignment Posted",
    message:
      "Complete the JavaScript project by Friday. Check the resources section for guidelines.",
    time: "2 hours ago",
    type: "assignment",
    date: "2024-01-20",
    courseId: "1",
    course: "Web Development Fundamentals",
    recipients: 67,
  },
  {
    id: 2,
    title: "Live Session Tomorrow",
    message:
      "Join us tomorrow at 2 PM for a live coding session on JavaScript functions.",
    time: "1 day ago",
    type: "schedule",
    date: "2024-01-19",
    courseId: "1",
    course: "Web Development Fundamentals",
    recipients: 67,
  },
];

// These functions simulate API calls, making it easy to swap them out later.
export const getAnnouncementsForCourse = (courseId: string): Announcement[] => {
  return mockCourseAnnouncements.filter((a) => a.courseId === courseId);
};

export const getCourseById = (id: string): Course | undefined => {
  const course = mockCourses.find((course) => course.id === id);
  return course;
};

export const getStudentById = (id: string): Student | undefined => {
  // In a real app, this would be a fetch. For now, we find in the mock array.
  // Assuming a full `mockStudents` array is populated.
  return undefined;
};

export const getMaterialsForCourse = (courseId: string): CourseMaterial[] => {
  return [
    {
      id: 1,
      title: "Introduction to HTML",
      type: "video",
      duration: "15:30",
      completed: true,
      url: "/videos/html-intro.mp4",
      description: "Learn the basics of HTML.",
    },
    {
      id: 2,
      title: "CSS Styling Basics",
      type: "video",
      duration: "22:45",
      completed: true,
      url: "#",
      description: "Master CSS fundamentals.",
    },
    {
      id: 3,
      title: "HTML Reference Guide",
      type: "pdf",
      size: "2.5 MB",
      pages: 45,
      completed: false,
      url: "#",
      description: "A comprehensive reference.",
    },
  ];
};
